FROM powerman/dockerize:0.19.0 AS dockerize
FROM node:18

WORKDIR /app

COPY --from=dockerize /usr/local/bin/dockerize /usr/local/bin/

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "start"]